name: Deploy Frontend
run-name: ${{ github.actor}} Frontend CI/CD demo
on: push

permissions:
  id-token: write
  contents: read

jobs:
  Deploy-Infra:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Terraform fmt
        id: tf-fmt
        working-directory: ./infra/frontend
        run: terraform fmt -check

      - name: Terraform init
        id: tf-init
        working-directory: ./infra/frontend
        run: |
          terraform init -input=false \
          -backend-config="bucket=${{ secrets.TFSTATE_BUCKET }}" \
          -backend-config="key=${{ secrets.TFSTATE_KEY }}" \
          -backend-config="dynamodb_table=${{ secrets.TFSTATE_DYNAMODB }}" \
          -backend-config="encrypt=true" \
          -backend-config="region=ap-southeast-2" \

      - name: Terraform Apply
        id: tf-apply
        working-directory: ./infra/frontend
        run: terraform apply -input=false -var-file=env/prod.tfvars
