name: Deploy Infra
on: push

permissions:
  id-token: write
  contents: read

jobs:
  Deploy-Infra:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}

      - name: Deploy with CDK
        run: echo "Hello World"

