name: Deploy Frontend
run-name: ${{ github.actor}} Frontend CI/CD demo
on: push

permissions:
  id-token: write
  contents: read

jobs:
  Deploy-Infra:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Terraform fmt
        id: tf-fmt
        working-directory: infra/frontend
        run: terraform fmt -check

      - name: Terraform init
        id: tf-init
        working-directory: infra/frontend
        run: terraform init -input=false
