name: Destroy
on:
  push:
    branches:
      - destroy

permissions:
  id-token: write
  contents: read

jobs:
  Deploy-Infra:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4


      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-southeast-2
          role-to-assume: ${{ secrets.AWS_GITHUB_ROLE }}

      - name: Configure Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.9.8"

      - name: Terraform fmt
        id: tf-fmt
        working-directory: infra/destroy
        run: terraform fmt -check

      - name: Terraform init
        id: tf-init
        working-directory: infra/destroy
        run: |
          terraform init -input=false \
          -backend-config="bucket=${{ secrets.TFSTATE_BUCKET }}" \
          -backend-config="key=${{ secrets.TFSTATE_KEY }}" \
          -backend-config="dynamodb_table=${{ secrets.TFSTATE_DYNAMODB }}" \
          -backend-config="encrypt=true" \
          -backend-config="region=ap-southeast-2" \

      - name: Terraform Workspace
        id: tf-workspace
        working-directory: infra/backend
        run: terraform workspace select -or-create backend

      - name: Terraform destroy
        id: tf-destroy
        working-directory: infra/destroy
        run: terraform apply -input=false -auto-approve -var-file=env/prod.tfvars

      - name: Terraform Default Workspace
        id: tf-workspace-default
        working-directory: infra/backend
        run: terraform workspace select default

      - name: Terraform Workspace Delete
        id: tf-workspace-delete
        working-directory: infra/destroy
        run: terraform workspace delete backend


